# Generated by Django 5.2.4 on 2025-07-18 15:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancerprofile',
            options={'verbose_name': 'Freelancer Profile', 'verbose_name_plural': 'Freelancer Profiles'},
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='campus_verified',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='student_id_card',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='availability',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', help_text='Current availability status', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to portfolio or personal website', null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description of the freelancer', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_freelancer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Django, JavaScript)', max_length=500),
        ),
    ]
