# Generated by Django 5.2.4 on 2025-07-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_alter_freelancerprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
