# Generated by Django 5.2.4 on 2025-08-20 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='confidentiality',
            field=models.BooleanField(default=True, help_text='Confidentiality agreement applies'),
        ),
        migrations.AddField(
            model_name='contract',
            name='dispute_resolution',
            field=models.CharField(default='Arbitration', help_text='How disputes will be resolved (e.g. Arbitration, Mediation, Court)', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected end date', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='governing_law',
            field=models.CharField(default='Ghanaian Law', help_text='Jurisdiction governing this contract', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='intellectual_property_transfer',
            field=models.BooleanField(default=True, help_text='Does the client own deliverables after payment?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_review', 'In Review'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.TextField(help_text='Full contract terms agreed by both parties.'),
        ),
    ]
