# Generated by Django 5.2.4 on 2025-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_confidentiality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttemplate',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='jurisdiction',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('in_review', 'In Review'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='Amendment',
        ),
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
