# Generated by Django 5.2.4 on 2025-07-18 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='budget_range',
            field=models.CharField(choices=[('LOW', '₵0 - ₵5,000'), ('MEDIUM', '₵5,001 - ₵20,000'), ('HIGH', '₵20,001+')], default='LOW', help_text='Typical project budget range', max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry or sector (e.g., Technology, Healthcare)', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_communication',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('VIDEO_CALL', 'Video Call'), ('CHAT', 'Chat')], default='EMAIL', help_text='Preferred communication method', max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='project_types',
            field=models.CharField(blank=True, help_text='Preferred project types (e.g., Web Development, Mobile Apps)', max_length=200),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text="Name of the client's company or organization", max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
