# Generated by Django 5.2.4 on 2025-07-18 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='job',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(help_text='The client making the payment', limit_choices_to={'is_client': True, 'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the transaction (e.g., project details)', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='freelancer',
            field=models.ForeignKey(help_text='The freelancer receiving the payment', limit_choices_to={'is_freelancer': True, 'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Transaction status', max_length=20),
        ),
    ]
