# Generated by Django 5.2.4 on 2025-07-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusservice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campus_attachments/'),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campusservice',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
