# Generated by Django 5.2.4 on 2025-08-09 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
        ('transactions', '0002_alter_transaction_options_remove_transaction_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrow',
            options={'verbose_name': 'Escrow', 'verbose_name_plural': 'Escrows'},
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='client',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='job',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='released_at',
        ),
        migrations.AddField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='HELD', help_text='Escrow status', max_length=20),
        ),
        migrations.AddField(
            model_name='escrow',
            name='transaction',
            field=models.OneToOneField(default=1, help_text='The transaction associated with this escrow', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='transactions.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount held in escrow', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='EscrowDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for the dispute', max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Dispute status', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on dispute resolution', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.ForeignKey(help_text='The escrow associated with this dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='escrow.escrow')),
                ('raised_by', models.ForeignKey(help_text='User who raised the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the dispute', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escrow Dispute',
                'verbose_name_plural': 'Escrow Disputes',
            },
        ),
    ]
